// this script is generated by chatGPT
  
  // Get the quote and author elements
  const quoteElement = document.getElementById("quote");
  const authorElement = document.getElementById("author");
  
  // Get the new quote button element
  const newQuoteBtn = document.getElementById("new-quote-btn");
  
  // Function to generate a random quote
function generateQuote() {
    // Load the quotes from the JSON file
    fetch("quotes.json")
      .then(response => response.json())
      .then(data => {
        // Get a random quote from the quotes array
        const randomIndex = Math.floor(Math.random() * data.length);
        const randomQuote = data[randomIndex];
        
        // Update the quote and author elements with the new quote
        quoteElement.textContent = `"${randomQuote.quote}"`;
        authorElement.textContent = `- ${randomQuote.author}`;
      })
      .catch(error => console.log(error));
  }
  
  
  // Add a click event listener to the new quote button
  newQuoteBtn.addEventListener("click", generateQuote);
  
  // Generate a quote when the page loads
  generateQuote();


