// this script is generated by chatGPT
  
  // Get the thought and source elements
  const quoteElement = document.getElementById("quote");
  const sourceElement = document.getElementById("source");
  
  // Get the new thought button element
  const newquoteBtn = document.getElementById("new-quote-btn");
  
  // Function to generate a random thought
function generatequote() {
    // Load the thoughts from the JSON file
    fetch("quotes.json")
      .then(response => response.json())
      .then(data => {
        // Get a random thought from the thoughts array
        const randomIndex = Math.floor(Math.random() * data.length);
        const randomquote = data[randomIndex];
        
        // Update the quote and source elements with the new thought
        quoteElement.textContent = `"${randomquote.quote}"`;
        sourceElement.textContent = `- ${randomquote.source}`;
      })
      .catch(error => console.log(error));
  }
  
  
  // Add a click event listener to the new thought button
  newquoteBtn.addEventListener("click", generatequote);
  
  // Generate a thought when the page loads
  generatequote();


